[package]
name = "resample"
version = "0.1.0"
edition = "2021"
description = "Sample rate conversion utilities for Harmoniq."
license = "GPL-3.0-or-later"

[dependencies]
serde = { workspace = true }
dsp = { path = "../dsp" }
simd = { path = "../simd" }
