[package]
name = "clap-plugin-authoring"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
clap-sys = { path = "../clap-sys" }
log = "0.4"
once_cell = "1.19"

[features]
default = []
