[package]
name = "clap-validate"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true }
clap-host = { path = "../clap-host" }
