[package]
name = "harmoniq-plugin-host"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
libloading = "0.8"
thiserror.workspace = true
serde = { workspace = true, optional = true }
