[package]
name = "harmoniq-app"
version = "0.1.0"
edition = "2021"

[dependencies]
harmoniq-audioio = { path = "../harmoniq-audioio" }
harmoniq-engine = { path = "../harmoniq-engine" }
harmoniq-ui = { path = "../harmoniq-ui" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
