[package]
name = "harmoniq-app"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
egui = { version = "0.27", features = ["serde"] }
crossbeam-channel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = []
