[package]
name = "harmoniq-plugin-sdk"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
harmoniq-engine = { path = "../harmoniq-engine" }
thiserror.workspace = true
serde.workspace = true
anyhow.workspace = true
