[package]
name = "midi"
version = "0.1.0"
edition = "2021"
description = "MIDI event utilities for Harmoniq."
license = "GPL-3.0-or-later"

[dependencies]
serde = { workspace = true }
engine-rt = { path = "../engine-rt" }
anyhow = { workspace = true }
