[package]
name = "harmoniq-midi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
midir = "0.10"
parking_lot = "0.12"
crossbeam-channel = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1"
dirs = "5"
tracing = "0.1"
