[package]
name = "harmoniq-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
harmoniq-engine = { path = "../harmoniq-engine", default-features = false }
