[package]
name = "multi-client-server"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
cpal = ["io-backends/cpal"]

[dependencies]
anyhow = { workspace = true }
engine-core = { path = "../../crates/engine-core" }
engine-graph = { path = "../../crates/engine-graph" }
io-backends = { path = "../../crates/io-backends" }
server = { path = "../../crates/server" }
dsp = { path = "../../crates/dsp" }
