name: CLAP Integration

on:
  push:
    branches: ["main", "feat/clap-vendored-integration"]
  pull_request:
    paths:
      - "crates/clap-sys/**"
      - "crates/clap-host/**"
      - "crates/clap-plugin-authoring/**"
      - "crates/clap-scanner/**"
      - "crates/clap-validate/**"
      - "examples/clap-testgain/**"
      - "examples/clap-testsynth/**"
      - "crates/harmoniq-engine/**"
      - "crates/harmoniq-plugin-bridge/**"
      - "third_party/clap/**"
      - ".github/workflows/clap.yml"

jobs:
  build:
    name: Build CLAP crates
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Build CLAP crates
        run: |
          cargo build -p clap-sys -p clap-host -p clap-plugin-authoring \
            -p clap-scanner -p clap-validate \
            -p clap-testgain -p clap-testsynth
      - name: Package test plug-ins
        run: |
          cargo build --release -p clap-testgain -p clap-testsynth
          echo "Artifacts generated in target/release"
